### PR TITLE
App remembers whether onboarding is done or not

### LINKED ISSUE #89: App should remember that I have done the onboarding
As now we are saving the data. App should remember that whether I have completed the on boarding or not.

If I have it should take me to home page Directly.

### PR DESCRIPTION
**Pull request by Rits1272**
Fixes #89
The app will directly navigate to `Dashboard` screen if on-boarding has been done already

WhatsApp-Video-2020-03-27-at-416

### CODE REVIEW

**Comment by Rits1272** [comment]
Please review @sarthology

**Comment by sarthology** [comment]
Also add a button to reset that for test purposes. 😅

**Comment by Rits1272** [comment]
Added the reset button. Please check @sarthology

**Comment by sahilit** [comment]
Great work @Rits1272

**Pull request merged**
