### PR TITLE
Changed png to text

### LINKED ISSUE #86: Use text instead on images in every page
Currently everyone is using pngs for the text in every page. Please use text instead. The font that we are using in already mention in [Design System](https://github.com/sarthology/ovuli/blob/master/designsystem.md).

It should look exactly the same.

### PR DESCRIPTION
**Pull request by Rits1272**
Fixes #86

### CODE REVIEW

**Comment by Rits1272** [comment]
Please review @sarthology

**Comment by sarthology** [comment]
Resolve conflicts

**Comment by Rits1272** [comment]
Resolved the conflicts. Please check @sarthology

**Comment by sarthology** [comment]
Still there

**Comment by Rits1272** [comment]
Resolved the conflicts again @sarthology. Please check

**Pull request merged**
