### PR TITLE
Avg Screen Build

### PR DESCRIPTION
**Pull request by Samriddhi25**
Resolving issue #7

### CODE REVIEW

**Comment by sarthology** [comment]
@Samriddhi25 @sushantag9 Please use better commit comments.

**Comment by Samriddhi25** [comment]
@sarthology please suggest me how to make the improvements for the commits.

**Comment by SarathSantoshDamaraju** [comment]
@Samriddhi25 @sushantag9 
Every commit message should have a short description on the purpose of the commit.

For the more standard ways of commit messages, refer any of the below
https://www.conventionalcommits.org/en/v1.0.0/#examples
https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716

**Comment by sarthology** [comment]
Congratulations on your first PR.

**Pull request merged**
