### PR TITLE
#9 done

### PR DESCRIPTION
**Pull request by vngarg**
Docusaurus Setup Done..

### CODE REVIEW

**Comment by sarthology** [comment]
You have to use the a clean slate from branch gh-pages in this repo.

**Comment by vngarg** [comment]
> You have to use the a clean slate from branch gh-pages in this repo.

What do you mean by clean slate ?

**Comment by sarthology** [comment]
Check the current gh-pages in the main repo

**Comment by vngarg** [comment]
> Check the current gh-pages in the main repo

So I have to do the work in existing gh-pages branch ?

**Pull request closed without merging**
