### PR TITLE
boarded pages

### PR DESCRIPTION
**Pull request by iharshit009**
Hi @sarthology,  this PR is referenced to #4 .

### CODE REVIEW

**Comment by sarthology** [comment]
Can you add the new pages to respective folders and use same nomenclature too like 
Screenshot 2020-03-01 at 1 19 44 AM

**Review by sarthology — CHANGES_REQUESTED** [review]
In the three files you added.

**Comment by iharshit009** [comment]
Okay

**Comment by iharshit009** [comment]
Please check out the changes @sarthology

**Comment by sarthology** [comment]
Great !! 
Congratulations on your first PR.

**Comment by adhavalboy** [comment]
@all-contributors please add @iharshit009 for code

**Comment by sarthology** [comment]
What ?

**Comment by adhavalboy** [comment]
its a bot! automatically make a list of the contributor.

**Pull request merged**
