### PR TITLE
resolves #5: Made StackNavigator

### LINKED ISSUE #5: Create stack navigation for on boarding
In this we have to add stacked [React Native Navigation](https://reactnavigation.org/docs/navigating) to pages added in #4.

### PR DESCRIPTION
**Pull request by Rits1272**

### CODE REVIEW

**Comment by Rits1272** [comment]
Solves issue #5 . Please review @sarthology

**Review by sarthology — CHANGES_REQUESTED** [review]
Stack Navigator should not be in the Profile screen. It will in App.js. As "Add your name" will be the first thing you will see when you open the app.

**Comment by Rits1272** [comment]
Okay @sarthology . I will make the changes

**Comment by Rits1272** [comment]
Made the changes @sarthology. Please check

**Comment by sarthology** [comment]
I'm checking. Please try to make commit more descriptive.

**Comment by Rits1272** [comment]
Okay will surely do it from next time

**Review by sarthology — CHANGES_REQUESTED** [review]
Please remove the package-lock.json from the PR as well.

**Comment by sarthology** [comment]
Also, this looks good to me for now. Good work champ. 👍🏽

Screenshot 2020-03-01 at 12 53 21 PM

**Comment by Rits1272** [comment]
Thanks @sarthology :)

> Please remove the package-lock.json from the PR as well.

I have already removed the package-lock.json file @sarthology

**Comment by sarthology** [comment]
Welcome on your first PR !! 
I hope more will come

**Pull request merged**
