### PR TITLE
Calendar Implemented in Last Period Screen

### LINKED ISSUE #8: Adding content to "Last period Page"
Here it will be a calendar. We will be using [this Calendar](https://github.com/wix/react-native-calendars) package. 

Possibly this

### PR DESCRIPTION
**Pull request by iharshit009**
The calendar is functional but there are improvements that would be suggested, Would implement those ASAP...
This PR is a reference to #8 , Kindly review it @sarthology

### CODE REVIEW

**Review by sarthology — CHANGES_REQUESTED** [review]
please remove package.json

**Comment by iharshit009** [comment]
@sarthology I have deleted it but could figure out why we are doing it?

**Comment by sarthology** [comment]
Because we are using YARN instead of NPM.

**Comment by sarthology** [comment]
Damn I meant package-lock.json

**Comment by iharshit009** [comment]
Yeah now I got it...

**Comment by iharshit009** [comment]
@sarthology look at the changes now...

**Comment by sarthology** [comment]
Looks good now.

**Pull request merged**
