### PR TITLE
Added Installation Guide for expo, to run app on mobile

### LINKED ISSUE #23: Adding Installation guide to Docusaurus
Adding documentation to run the app locally on phone using expo, including screenshots

**Note:**
- _The branch in gh-pages_
- _Read more about Docusaurus [here](https://docusaurus.io/docs/en/installation)_

### PR DESCRIPTION
**Pull request by vngarg**
# Description 
Closes the issue #23.
I had added a README.md file which includes all the neccesary details to setup the environment to run the app locally on mobile device ..

### CODE REVIEW

**Review by sarthology — CHANGES_REQUESTED** [review]
The guide was to run the app locally. Check the description on #32

**Comment by vngarg** [comment]
> The guide was to run the app locally. Check the description on #32

Later steps including - 
1. Moving to folder 'website'
2. running npm start
These are the steps which run the app locally.

**Comment by sarthology** [comment]
I meant the mobile app

**Comment by vngarg** [comment]
I had updated the required changes.
Please review these changes

**Pull request merged**
