### PR TITLE
png to svg

### LINKED ISSUE #143: Replace the PNG icons with SVG icons
image

### PR DESCRIPTION
**Pull request by shreyakapoor08**
Fix #143 
Replaced png icon with svg icons.

### CODE REVIEW

**Comment by shreyakapoor08** [comment]
@sahilit Kindly check

**Comment by sahilit** [comment]
Please resolve the conflicts.

**Comment by shreyakapoor08** [comment]
> Please resolve the conflicts.

Please check if it is correct now @sahilit

**Comment by sahilit** [comment]
The SVG is not visible because SVGs in native are not as simple as it is in HTML/Web, where you can use SVG as an image or copy-paste SVG content. 

Follow this article:
https://medium.com/faun/add-custom-svg-icons-to-your-expo-app-279b492f6a15

**Pull request merged**
