### PR TITLE
Fix: Name Screen Design

### LINKED ISSUE #72: Change Design of add name page
Change this 
image
to this

See `wireframes/assets` folder and use SVG icons.

### PR DESCRIPTION
**Pull request by Major2001**
Changed the Design of name screen and removed the unnecessary errors

### CODE REVIEW

**Comment by Major2001** [comment]
Fixed #72

**Comment by sarthology** [comment]
Please resolve the conflicts.

**Comment by Major2001** [comment]
Done!

**Comment by sarthology** [comment]
Good Job !!!

**Pull request merged**
