### PR TITLE
Calculations using ovuli library

### LINKED ISSUE #65: Use saved data to calculations using ovuli.js
#56 Allows to store data Locally. Let's use the same library now to use the data to give results. You may use ovuli.js (Already Present in the `src/util` folder).

### PR DESCRIPTION
**Pull request by Rits1272**
A user will now be able to see Approximate Ovulation date, Next Period Date, Next Pregnancy Date and Fertile Window. These calculations are being done using the **calculateOvuli** function present in the ovuli library

### CODE REVIEW

**Comment by Rits1272** [comment]
Closes #65. Please review @sarthology

**Comment by sarthology** [comment]
@Rits1272 Gif for it

**Comment by Rits1272** [comment]
Please check @sarthology 

VID-20200319225620

**Comment by sarthology** [comment]
Fabulous Speed Champ !!

**Pull request merged**
