### PR TITLE
#9 done

### LINKED ISSUE #9: Adding documentation using docusaurus
Setting up docusaurus in a separate branch.

Follow [Installation](https://docusaurus.io/docs/en/installation) here.

Remember it will a separate branch entirely names "gh-pages" so work wisely.

### PR DESCRIPTION
**Pull request by vngarg**

### CODE REVIEW

**Comment by sarthology** [comment]
Please use proper Description and title for you PR.

**Comment by sarthology** [comment]
Still has all the files from master.

Screenshot 2020-03-01 at 2 36 54 PM

**Comment by sarthology** [comment]
Here are steps:
- Delete gh-pages branch on your forked repo.
- Take pull from main repo 
- Install Docusaurus
- Send the PR

**Comment by vngarg** [comment]
> Here are steps:
> 
> * Delete gh-pages branch on your forked repo.
> * Take pull from main repo
> * Install Docusaurus
> * Send the PR

My PR should only have Docusaurus on it ?
Do I have to make PR to master or gh-pages ?

**Pull request closed without merging**
